### API 1 - to register
POST http://localhost:3004/register
Content-Type: application/json

{
  "username": "adam_richard",
  "name": "Adam Richard",
  "password": "richard_567",
  "gender": "male",
  "location": "Detroit"
}




### API 2 - to login
POST http://localhost:3002/login 
Content-Type: application/json 

{
  "username": "adam_richard",
  "password": "richard_567"
}





###API 4 -to get  
GET http://localhost:3004/posts/1/ 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1fcmljaGFyZCIsImlhdCI6MTYyNjQ2MDk4NX0.C4BJ71B0Vvw7Uo2pLPIblrw-pg55xP2jDkCUPmn1Nd8